name: CI

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Décoder le keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build APK Release
        uses: kivy/buildozer-action@master
        with:
          buildozer_command: android release -v
          keystore_path: keystore.jks
          keystore_password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          key_password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MathQuizComores
          path: bin/*.apk
