name: Build APK Math Quiz Comores

on:
  push:
    branches: [ principal, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install deps
      run: sudo apt update && sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Buildozer
      run: pip install buildozer cython==0.29.33

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: buildozer-cache-armv7a-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-cache-armv7a-${{ runner.os }}-

    - name: Pre-build to download SDK/NDK
      run: yes | buildozer android debug || true

    - name: Decode Keystore
      run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ma-cle-de-developpement.keystore

    - name: Build APK Release Unsigned
      run: buildozer android release
      
    - name: Vérifier le Keystore
      run: |
       keytool -list -v -keystore ma-cle-de-developpement.keystore -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

    - name: Installer les dépendances zipalign
      run: sudo apt-get update && sudo apt-get install -y zlib1g

    - name: Signer et Aligner APK Buildozer
      run: |
       ls bin/
       jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
       -keystore ma-cle-de-developpement.keystore \
       -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
       -keypass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
       bin/*-release-unsigned.apk \
       mon-alias
       ${ANDROID_SDK_ROOT}/build-tools/34.0.0/zipalign -v 4 \
       bin/*-release-unsigned.apk \
       bin/quizapp_comores-v${{ github.run_number }}-signed.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MathQuizComores-v${{ github.run_number }}-armv7a-signed
        path: bin/*-signed.apk
